const Router = require('express')
const router = new Router()

const authRouter = require('./users.route')
const phonesRouter = require('./phones.route')
const payslipRouter = require('./payslip.route')
const messagesRouter = require('./messages.route')
const t13Router = require('./t13.route')
const objsRouter = require('./objs.route')
const weldingRouter = require('./welding.route')
const odataRouter = require('./odata.route')
const filesRouter = require('./files.route')
const pollsRouter = require('./polls.route')
const postsRouter = require('./posts.route')
const tasksRouter = require('./tasks.route')
const tabelRouter = require('./tabel.route')
const manRouter = require('./mans.route')
const referenceRouter = require('./reference.route')
const socialityRouter = require('./sociality.route')
const notificationsRouter = require('./notifications.route')

router.use('/auth',authRouter)
router.use('/phones',phonesRouter)
router.use('/objects',objsRouter)
router.use('/welding',weldingRouter)
router.use('/payslip',payslipRouter)
router.use('/mess',messagesRouter)
router.use('/t13',t13Router)
router.use('/odata',odataRouter)
router.use('/files',filesRouter)
router.use('/polls',pollsRouter)
router.use('/posts',postsRouter)
router.use('/tasks',tasksRouter)
router.use('/tabel',tabelRouter)
router.use('/mans',manRouter)
router.use('/reference',referenceRouter)
router.use('/sociality',socialityRouter)
router.use('/notifications',notificationsRouter)

module.exports = router